name: Beta Release

on:
  workflow_dispatch:
    inputs:
      reference:
          type: text
          required: false
          description: Optional Alpha Version
          default: ''

jobs:
  startup:
    name: Startup
    environment: beta
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-startup@main
        with:
          stage: beta
          reference: ${{ github.event.inputs.reference }}
          token: ${{ secrets.BOT_PAT }}

  build:
    name: Build
    needs: [startup]
    uses: ./.github/workflows/build-job.yaml

  deploy:
    name: Deploy
    needs: [build]
    uses: NoorDigitalAgency/.github/.github/workflows/deploy.yaml@main
    with:
      deployment_folder_artifact: deployment-artifact
      stage: beta
      # TODO: Add resource_type: deployment if needed otherwise remove this TODO (Defaults to daemonset)
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      kube_config: ${{ secrets.### }} # TODO: Replace ### with SERVER63_KUBE_CONFIG (for the physical server) or LJN1_KUBE_CONFIG (for the cluster)

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ github.token }}
      - uses: NoorDigitalAgency/release-publish@main
        with:
          stage: beta
          token: ${{ github.token }}

  uncache:
    name: Uncache
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/cloudflare-uncache@main
        with:
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domain: ${{ secrets.STAGE_DOMAIN }}
