name: Beta Release

on:
  workflow_dispatch:
    inputs:
      reference:
          type: text
          required: false
          description: Optional Alpha Version
          default: ''

jobs:
  startup:
    name: Startup
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-startup@main
        with:
          stage: beta
          reference: ${{ github.event.inputs.reference }}
          token: ${{ secrets.PAT }}

  build:
    name: Build
    needs: [startup]
    uses: ./.github/workflows/build-job.yaml # TODO: Check to match the correct file name
    with:
      stage: beta
    secrets: inherit

  migrate:
    name: Migrate Database
    needs: [build]
    uses: NoorDigitalAgency/.github/.github/workflows/ef-migrations.yaml@main
    with:
      project: ./Project/Project.csproj # TODO: Update this path to the project containing code for DbContext
      arguments: --startup-project DbContextName # TODO: Remove if not needed or update to pass in the extra arguments needed for the bundle command
    secrets:
      connection_string: ${{ secrets.SQL_CONNECTION_STRING }} # TODO: Update this to refer to the intended connection string secret

  deploy:
    name: Deploy
    needs: [migrate]
    uses: NoorDigitalAgency/.github/.github/workflows/deploy.yaml@main
    with:
      deployment_folder_artifact: deployment-artifact
      stage: beta
      resource_namespace: default # TODO: Update if needed
      # TODO: Add "resource_type: deployment" if needed otherwise remove this TODO (Defaults to daemonset)
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      kube_config: ${{ secrets.KUBE_CONFIG }}

  release:
    name: Release
    needs: [migrate]
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ github.token }}
      - uses: NoorDigitalAgency/release-publish@main
        with:
          stage: beta
          token: ${{ github.token }}

  uncache:
    name: Uncache
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/cloudflare-uncache@main
        with:
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domain: jobdev.se # TODO: Update accordingly

  mark:
    name: Mark Issues
    needs: [deploy,release]
    uses: NoorDigitalAgency/.github/.github/workflows/mark-issues.yaml@main
    secrets:
      token: ${{ secrets.PAT }}
