name: .NET Build Job

on:
  workflow_call:
    inputs:
      stage:
        description: Current stage name
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - if: github.event_name != 'pull_request'
        uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name != 'pull_request' && env.RELEASE_REFERENCE || github.event.pull_request.head.ref }}
          submodules: recursive
          token: ${{ secrets.PAT }}

      - uses: actions/setup-dotnet@v2
        with:
          source-url: https://nuget.pkg.github.com/noordigitalagency/index.json
          dotnet-version: '6.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PAT }}

      - uses: dopplerhq/cli-action@v1

      # TODO: Change the 'cd .' command to point to the directory where the appsettings files exist
      - run: |
          cd .
          [ '${{ inputs.stage }}' == 'alpha' ] && doppler secrets substitute appsettings.develop.json.tmpl --output appsettings.develop.json || \
          [ '${{ inputs.stage }}' == 'beta' ] && doppler secrets substitute appsettings.release.json.tmpl --output appsettings.release.json || \
          [ '${{ inputs.stage }}' == 'production' ] && doppler secrets substitute appsettings.production.json.tmpl --output appsettings.production.json
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      - run: |
          # Tip: Add extra nuget sources like 'dotnet nuget add source https://www.myget.org/F/cachemanager/api/v3/index.json -n myget'
          dotnet publish -c Release -r ubuntu-x64 -o outputs -p:InformationalVersion=${{ env.RELEASE_VERSION }} ./project.csproj # TODO: Correct the path to the project file

      - uses: actions/upload-artifact@v3
        with:
          name: deployment-artifact
          retention-days: 2
          path: |
            Dockerfile
            outputs
