name: Build Job

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ secrets.token }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_REFERENCE }}
          submodules: recursive
          token: ${{ secrets.token }}

      # TODO: Steps for building the source

      - uses: actions/upload-artifact@v3
        with:
          name: deployment-artifact
          retention-days: 2
          # TODO: Add path to assets used in the deployment. For details on 'path' refer to https://github.com/actions/upload-artifact#usage
          path: |
            Dockerfile
            outputs
