name: Entity Framework Migrations

on:
  workflow_call:
    inputs:
      stage:
        description: Current stage name
        required: true
        type: string

jobs:
  migrate:
    name: Migrate Database
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}
          ref: ${{ env.RELEASE_REFERENCE }}

      - uses: actions/setup-dotnet@v2
        with:
          source-url: https://nuget.pkg.github.com/noordigitalagency/index.json
          dotnet-version: 6.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.PAT }}

      # TODO: Modify this to point to the missing file
      - run: mv ./data-project/datasettings.json.tmpl ./data-project/datasettings.json

      - run: |
          dotnet new tool-manifest
          dotnet tool install --global dotnet-ef --version 6.0.*

      - run: dotnet ef migrations bundle --project ./project # TODO: Update the arguments passed to the command

      - run: |
          chmod +x ./efbundle
          sudo sed -i '/\[\s*new_oids\s*\]/i openssl_conf = openssl_init\n[openssl_init]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nMinProtocol = TLSv1.2\nCipherString = DEFAULT@SECLEVEL=2\n' /etc/ssl/openssl.cnf

      - env:
          OPENVPN_CONFIG: ${{ secrets.OPENVPN_CONFIG }}
          OPENVPN_USERNAME: ${{ secrets.OPENVPN_USERNAME }}
          OPENVPN_PASSWORD: ${{ secrets.OPENVPN_PASSWORD }}
        run: |
          [[ ! -z "$OPENVPN_CONFIG" ]] && [[ ! -z "$OPENVPN_USERNAME" ]] && [[ ! -z "$OPENVPN_PASSWORD" ]] && \
          sudo apt install apt-transport-https && wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub && sudo apt-key add openvpn-repo-pkg-key.pub && \
          sudo wget -O /etc/apt/sources.list.d/openvpn3.list "https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$(lsb_release -c -s).list" && \
          sudo apt update && sudo apt install openvpn3 && echo "$OPENVPN_CONFIG" > config.ovpn && echo "$OPENVPN_USERNAME" > config.login && echo "$OPENVPN_PASSWORD" >> config.login && \
          openvpn3 session-start --config config.ovpn && echo "TUNNEL_CONNECTION=established" >> $GITHUB_ENV || echo

      - run: ./efbundle --connection "${{ secrets.SQL_CONNECTION_STRING }}" # TODO: Update this to refer to the intended connection string secret

      - if: ${{ always() }}
        run: echo && [ '${{ env.TUNNEL_CONNECTION }}' == 'established' ] && openvpn3 session-manage --disconnect --config config.ovpn || echo