name: Hotfix Release

on:
  workflow_dispatch:
    inputs:
      reference:
          type: string
          required: true
          description: Hotfix Branch Name

jobs:
  startup:
    name: Startup
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-startup@main
        with:
          stage: production
          reference: ${{ github.event.inputs.reference }}
          token: ${{ secrets.PAT }}
          hotfix: true

  build:
    name: Build
    needs: [startup]
    uses: ./.github/workflows/build-job.yaml # TODO: Check to match the correct file name
    with:
      stage: production
    secrets: inherit

  test:
    name: Test
    needs: [startup]
    uses: ./.github/workflows/test-job.yaml # TODO: Check to match the correct file name
    with:
      stage: production
    secrets: inherit

  migrate:
    name: Migrate Database
    needs: [build,test]
    uses: .github/workflows/ef-migrations.yaml # TODO: Check to match the correct file name
    secrets: inherit

  deploy:
    name: Deploy
    needs: [migrate]
    uses: NoorDigitalAgency/.github/.github/workflows/deploy.yaml@main
    with:
      deployment_folder_artifact: deployment-artifact
      stage: production
      resource_namespace: default # TODO: Update if needed
      # TODO: Add "resource_type: deployment" if needed otherwise remove this TODO (Defaults to daemonset)
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      kube_config: ${{ secrets.KUBE_CONFIG }}

  release:
    name: Release
    needs: [migrate]
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ github.token }}
      - uses: NoorDigitalAgency/release-publish@main
        with:
          stage: production
          token: ${{ github.token }}

  uncache:
    name: Uncache
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/cloudflare-uncache@main
        with:
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domain: jobdev.se # TODO: Update accordingly
      - uses: NoorDigitalAgency/cloudflare-uncache@main # NOTE: Example of un-caching multiple domains
        with:
          api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domain: job-api.se # TODO: Update accordingly

  post-hotfox:
    name: Post Hotfix
    needs: [deploy]
    uses: NoorDigitalAgency/.github/.github/workflows/post-hotfix.yaml@main
    with:
      hotfix_branch: ${{ github.event.inputs.reference }}
