name: Downgrade Action

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version to downgrade to

jobs:
  version-check:
    name: Version Check
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.check.outputs.result }}
    steps:
      - name: Chcek
        id: check
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const version = '${{ github.event.inputs.version }}';
            if (!/^v20\d{2}(?:\.\d{1,3}){1,2}(?:(?:-alpha\.|-beta\.)\d{1,3})?$/.test(version))
            {
              core.setFailed(`Invalid version "${version}".`);
            }
            else
            {
              return version.includes('-alpha.') ? 'alpha' : version.includes('-beta.') ? 'beta' : 'production';
            }

  downgrade:
    name: Downgrade
    needs: [version-check]
    uses: NoorDigitalAgency/.github/.github/workflows/downgrade.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      stage: ${{ needs.version-check.stage }}

  re-deploy:
    name: Re-deploy
    needs: [version-check]
    uses: NoorDigitalAgency/.github/.github/workflows/re-deploy.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      stage: ${{ needs.version-check.stage }}
      resource_namespace: default # TODO: Update if needed
      # TODO: Add "resource_type: deployment" if needed otherwise remove this TODO (Defaults to daemonset)
    secrets: inherit
