name: Downgrade

on:
  workflow_dispatch:
    inputs:
      version:
        type: text
        required: true
        description: Version to downgrade to

jobs:
  version-check:
    name: Version Check
    runs-on: ubuntu-x64
    outputs:
      environment: ${{ steps.check.outputs.result }}
    steps:
      - name: Chcek
        id: check
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const version = '${{ github.event.inputs.version }}';
            if (!/^v20\d{2}(?:\.\d{1,3}){1,2}(?:(?:-alpha\.|-beta\.)\d{1,3})?$/.test(version))
            {
              core.setFailed(`Invalid version "${version}".`);
            }
            else
            {
              return version.includes('-alpha.') ? 'alpha-downgrade' : version.includes('-beta.') ? 'beta-downgrade' : 'production-downgrade';
            }

  downgrade:
    name: Downgrade
    needs: [version-check]
    uses: NoorDigitalAgency/.github/.github/workflows/downgrade.yaml@main
    with:
      version: ${{ github.event.inputs.version }}
      environment: ${{ needs.version-check.environment }}
