name: JavaScript Build Job

on:
  workflow_call:
    inputs:
      stage:
        description: Current stage name
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - if: github.event_name != 'pull_request'
        uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name != 'pull_request' && env.RELEASE_REFERENCE || github.event.pull_request.head.ref }}
          submodules: recursive
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16' # TODO: Set to the correct version

      - run: |
          echo -e "@noordigitalagency:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=$TOKEN\n" > ~/.npmrc
          npm install
          [ '${{github.event_name}}' != 'pull_request' ] && npm version ${{ env.RELEASE_EXTENDED_VERSION }} --no-commit-hooks --no-git-tag-version || echo
        env:
          TOKEN: ${{ secrets.PAT }}

      - run: npm run build -- --mode $([ '${{ inputs.stage }}' == 'alpha' ] && echo 'develop' || ([ '${{ inputs.stage }}' == 'beta' ] && echo 'release' || echo 'production'))

      - if: github.event_name != 'pull_request'
        uses: noordigitalagency/artifact-upload@main
        with:
          name: deployment-artifact
          key: ${{ secrets.BACKBLAZE_KEY }}
          id: ${{ secrets.BACKBLAZE_ID }}
          bucket: ${{ secrets.BACKBLAZE_BUCKET }}
          path: |
            Dockerfile
            dist
            default.conf
