name: JavaScript Test Job

on:
  workflow_call:
    inputs:
      stage:
        description: Current stage name
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - if: github.event_name != 'pull_request'
        uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event_name != 'pull_request' && env.RELEASE_REFERENCE || github.event.pull_request.head.ref }}
          submodules: recursive
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16' # TODO: Set to the correct version

      - run: |
          echo -e "@noordigitalagency:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=$TOKEN\n" > ~/.npmrc
          npm install
        env:
          TOKEN: ${{ secrets.PAT }}

      - run: npm run test

       # TODO: Correct the report file path
      - if: ${{ always() }}
        run: |
          [ -f "test-reports.html" ] && \
            cat "test-reports.html" >> $GITHUB_STEP_SUMMARY || \
            echo "::warning::No Unit Test results were found in the project!"
