name: NPM Publish Job

on:
  workflow_call:
    inputs:
      stage:
        description: Current stage name
        required: true
        type: string

jobs:
  publish:
    name: Publish NPM
    runs-on: ubuntu-latest
    environment: ${{ inputs.stage }}
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_REFERENCE }}
          submodules: recursive
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16' # TODO: Set to the correct version

      - run: |
          echo -e "@noordigitalagency:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=$TOKEN\n" > ~/.npmrc
          npm install
          npm version ${{ env.RELEASE_EXTENDED_VERSION }} --no-commit-hooks --no-git-tag-version
        env:
          CI: true
          TOKEN: ${{ secrets.PAT }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
