name: PR Check

on:
  pull_request:
    branches: [develop]
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    uses: ./.github/workflows/test-job.yaml # TODO: Check to match the correct file name
    secrets: inherit

  build:
    uses: ./.github/workflows/build-job.yaml # TODO: Check to match the correct file name
    with:
      stage: alpha
    secrets: inherit

  reviewers:
    uses: NoorDigitalAgency/.github/.github/workflows/reviewers.yaml@main
    with:
      strict: false # TODO: Set to true if reviews are mandetory
