name: Test Job

on:
  workflow_call:
    secrets:
      # TODO: Add all the placeholder variables, example:
      #alpha-sql-password:
        #required: true
      #beta-sql-password:
        #required: true
      token:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # Note: Local SQL Server for DB tests
    services:
      sql-server:
        image: noorteam/mssql-docker:2019-focal
        ports:
          - 1433:1433
        env:
          DATABASE_USERNAME: user
          DATABASE_NAMES: database # Note: You can add multiple databases like postnoor, golight, lynx
        options: --health-cmd sqlserver_isready

    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_REFERENCE }}
          submodules: recursive
          token: ${{ secrets.token }}

      - uses: actions/setup-dotnet@v2
        with:
          source-url: https://nuget.pkg.github.com/noordigitalagency/index.json
          dotnet-version: '6.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.token}}

      - name: Add Alpha secrets
        # TODO: Correct the path to the file
        run: |
          envsubst < ./appsettings.develop.json | tee ./appsettings.develop.json
        env:
          # TODO: Add all the placeholder variables, example:
          #SQL_PASSWORD: ${{ secrets.alpha-sql-password }}

      - name: Add Beta secrets
        # TODO: Correct the path to the file
        run: |
          envsubst < ./appsettings.release.json | tee ./appsettings.release.json
        env:
          # TODO: Add all the placeholder variables, example:
          #SQL_PASSWORD: ${{ secrets.beta-sql-password }}

      - name: Add Production secrets
        # TODO: Correct the path to the file
        run: |
          envsubst < ./appsettings.production.json | tee ./appsettings.production.json
        env:
          # TODO: Add all the placeholder variables, example:
          #SQL_PASSWORD: ${{ secrets.production-sql-password }}

      - run: |
          # Tip: Add extra nuget sources like 'dotnet nuget add source https://www.myget.org/F/cachemanager/api/v3/index.json -n myget'
          cd ./Tests/ # TODO: Correct this to the tests project folder
          mkdir ./test-results
          dotnet test --logger "trx;logfilename=$(pwd)/test-results/test-reports.trx"
          dotnet tool install --global LiquidTestReports.Cli --version 1.3.2-beta
          liquid --inputs "File=$(pwd)/test-results/test-reports.trx;Format=Trx" --output-file test-reports.md

      - uses: actions/upload-artifact@v3
        with:
          name: deployment-artifact
          retention-days: 30
          path: |
            test-reports.md