name: Test Job

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/midday@main
        with:
          token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_REFERENCE }}
          submodules: recursive
          
      # TODO: Steps for testing the code
