name: Test Job

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ secrets.token }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_REFERENCE }}
          submodules: recursive

      # TODO: Steps for testing the code
