name: Assign Pull Request Reviewers

on:
  workflow_call:
    inputs:
      strict:
        description: Throws error on assignment failure
        default: true
        
jobs:
  assign:
    runs-on: ubuntu-latest
    name: Assign Reviewers
    steps:
      - run: echo
