name: Mark Issues

on:
  workflow_call:
    inputs:
      close-issues:
        description: Close Issues on Merge to Production
        type: boolean
        default: true
        required: false
    secrets:
      token:
        description: Token
        required: true

jobs:
  mark:
    name: Mark Issues
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0
          ref: ${{ env.RELEASE_VERSION }}
      - uses: NoorDigitalAgency/issue-marker@main
        with:
          token: ${{ secrets.token }}
          reference: ${{ env.RELEASE_REFERENCE }}
          version: ${{ env.RELEASE_VERSION }}
          previous-version: ${{ env.RELEASE_PREVIOUS_VERSION }}
          close-issues: ${{ inputs.close-issues }}
