name: Mark Issues

on:
  workflow_call:
    inputs:
      close-issues:
        description: Close Issues on Merge to Production
        type: boolean
        default: true
        required: false
      artifact-name:
        description: Release Artifact Name
        type: string
        default: release-startup-outputs
        required: false

jobs:
  mark:
    name: Mark Issues
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ secrets.PAT }}
          artifact_name: ${{ inputs.artifact-name }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          ref: ${{ env.RELEASE_VERSION }}
      - uses: NoorDigitalAgency/issue-marker@main
        with:
          token: ${{ secrets.PAT }}
          reference: ${{ env.RELEASE_REFERENCE }}
          version: ${{ env.RELEASE_VERSION }}
          previous-version: ${{ env.RELEASE_PREVIOUS_VERSION }}
          close-issues: ${{ inputs.close-issues }}
          zenhub-key: ${{ secrets.ZENHUB_KEY }}
          zenhub-workspace: ${{ secrets.ZENHUB_WORKSPACE }}
