name: Publish GitHub Action

on:
  workflow_call:
    inputs:
      branch:
        description: Branch to checkout
        type: string
        default: 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0
        token: ${{ github.token || secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: |
        npm i
        npm run all
        git config --global user.name "Noor's GitHub Bot"
        git config --global user.email "noorgithubbot@github"
        git add -A
        git commit -m "Automated build and publish"
        git push
