name: Worker Jump Release

on:
  workflow_call:
    inputs:
      worker:
        description: The caller is a worker
        type: boolean
        required: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - run: echo "inputs.worker: ${{ inputs.worker }}"

  startup:
    if: inputs.worker == true
    name: Startup
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-startup@main
        with:
          stage: beta
          reference: ${{ github.event.inputs.reference }}
          token: ${{ secrets.PAT }}
          artifact_name: dotnet-worker-jump-release-artifact

  release:
    if: inputs.worker == true
    name: Release
    needs: [startup]
    runs-on: ubuntu-latest
    steps:
      - uses: NoorDigitalAgency/release-lookup@main
        with:
          token: ${{ github.token }}
          artifact_name: dotnet-worker-jump-release-artifact
      - uses: NoorDigitalAgency/release-publish@main
        with:
          stage: beta
          token: ${{ github.token }}

  mark:
    if: inputs.worker == true
    name: Mark Issues
    needs: [release]
    uses: NoorDigitalAgency/.github/.github/workflows/mark-issues.yaml@main
    secrets: inherit
