name: Worker Jump Release

on:
  workflow_call:
    inputs:
      reference:
        description: The reference set on the caller workflow call
        type: string
        required: true
      worker:
        description: If the caller is a worker
        type: boolean
        required: true

    outputs:
      reference:
        description: The reference to be used by the caller's startup job
        value: ${{ jobs.jump.outputs.reference }}

jobs:
  jump:
    name: Jump
    runs-on: ubuntu-latest
    outputs:
      reference: ${{ steps.reference.outputs.reference }}
    steps:
      - if: inputs.worker == true
        uses: NoorDigitalAgency/release-startup@main
        with:
          stage: beta
          reference: ${{ inputs.reference }}
          token: ${{ secrets.PAT }}
          artifact_name: dotnet-worker-jump-release-artifact

      - if: inputs.worker == true
        uses: NoorDigitalAgency/release-publish@main
        with:
          stage: beta
          token: ${{ secrets.PAT }}
          artifact_name: dotnet-worker-jump-release-artifact

      - if: inputs.worker == true
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          ref: ${{ env.RELEASE_VERSION }}

      - if: inputs.worker == true
        uses: NoorDigitalAgency/issue-marker@main
        with:
          token: ${{ secrets.PAT }}
          reference: ${{ env.RELEASE_REFERENCE }}
          version: ${{ env.RELEASE_VERSION }}
          previous-version: ${{ env.RELEASE_PREVIOUS_VERSION }}

      - id: reference
        run: echo "reference=$([ '${{ inputs.worker }}' == 'true' ] && echo '${{ env.RELEASE_VERSION }}' || echo '${{ inputs.reference }}')" >> $GITHUB_OUTPUT
